import { business } from "./business";

export const reviewStats = {
  average: business.rating,
  total: business.reviewCount,
  distribution: {
    5: 4,
    4: 2,
    3: 1,
    2: 0,
    1: 0,
  },
};

export const reviews = [
  {
    id: 1,
    name: 'Priya Sharma',
    rating: 5,
    text: 'Absolutely fantastic service! The team was professional, thorough, and left my home sparkling. Will definitely book again.',
    service: 'Deep Cleaning',
    location: 'CIDCO, Nashik',
    date: '2026-06-15',
    verified: true,
    visible: true,
  },
  {
    id: 2,
    name: 'Rahul Patil',
    rating: 5,
    text: 'Best cleaning service I have ever used. They went above and beyond, even cleaning areas I did not expect. Highly recommend!',
    service: 'Regular Cleaning',
    location: 'Ambad, Nashik',
    date: '2026-06-12',
    verified: true,
    visible: true,
  },
  {
    id: 3,
    name: 'Sneha Kulkarni',
    rating: 4,
    text: 'Great attention to detail and very punctual. The only reason for 4 stars is that they arrived slightly late, but the quality made up for it.',
    service: 'Move-in Cleaning',
    location: 'Gangapur Road, Nashik',
    date: '2026-06-10',
    verified: true,
    visible: true,
  },
  {
    id: 4,
    name: 'Amit Deshmukh',
    rating: 5,
    text: 'Incredible transformation. My apartment looks brand new after their deep cleaning service. Worth every penny!',
    service: 'Deep Cleaning',
    location: 'College Road, Nashik',
    date: '2026-06-08',
    verified: true,
    visible: true,
  },
  {
    id: 5,
    name: 'Neha Joshi',
    rating: 5,
    text: 'The team was friendly, efficient, and respectful of my home. They used eco-friendly products which I really appreciate.',
    service: 'Green Cleaning',
    location: 'Satpur, Nashik',
    date: '2026-06-05',
    verified: true,
    visible: true,
  },
  {
    id: 6,
    name: 'Vikram Singh',
    rating: 4,
    text: 'Solid cleaning service. Professional staff and good communication throughout. Would use again for regular maintenance.',
    service: 'Regular Cleaning',
    location: 'Panchavati, Nashik',
    date: '2026-06-03',
    verified: true,
    visible: true,
  },
  {
    id: 7,
    name: 'Anita Pawar',
    rating: 5,
    text: 'Outstanding work! They cleaned my office space and it looks immaculate. The attention to detail is remarkable.',
    service: 'Commercial Cleaning',
    location: 'Canada Corner, Nashik',
    date: '2026-06-01',
    verified: true,
    visible: true,
  },
  {
    id: 8,
    name: 'Suresh Gaikwad',
    rating: 4,
    text: 'Good service overall. The team was polite and did a thorough job cleaning my 2BHK apartment. Fair pricing too.',
    service: 'Regular Cleaning',
    location: 'Dwarka, Nashik',
    date: '2026-05-28',
    verified: true,
    visible: true,
  },
];
