import { business } from "./business";

export const reviewStats = {
  average: business.rating,
  total: business.reviewCount,
  distribution: {
    5: 85,
    4: 10,
    3: 3,
    2: 1,
    1: 1,
  },
};

export const reviews = [
  {
    id: 1,
    name: 'Sarah Johnson',
    rating: 5,
    text: 'Absolutely fantastic service! The team was professional, thorough, and left my home sparkling. Will definitely book again.',
    service: 'Deep Cleaning',
    location: 'New York, NY',
    date: '2026-06-15',
    verified: true,
    visible: true,
  },
  {
    id: 2,
    name: 'Michael Chen',
    rating: 5,
    text: 'Best cleaning service I have ever used. They went above and beyond, even cleaning areas I did not expect. Highly recommend!',
    service: 'Regular Cleaning',
    location: 'Brooklyn, NY',
    date: '2026-06-12',
    verified: true,
    visible: true,
  },
  {
    id: 3,
    name: 'Emily Rodriguez',
    rating: 4,
    text: 'Great attention to detail and very punctual. The only reason for 4 stars is that they arrived slightly late, but the quality made up for it.',
    service: 'Move-in Cleaning',
    location: 'Queens, NY',
    date: '2026-06-10',
    verified: true,
    visible: true,
  },
  {
    id: 4,
    name: 'David Thompson',
    rating: 5,
    text: 'Incredible transformation. My apartment looks brand new after their deep cleaning service. Worth every penny!',
    service: 'Deep Cleaning',
    location: 'Manhattan, NY',
    date: '2026-06-08',
    verified: false,
    visible: true,
  },
  {
    id: 5,
    name: 'Lisa Park',
    rating: 5,
    text: 'The team was friendly, efficient, and respectful of my home. They used eco-friendly products which I really appreciate.',
    service: 'Green Cleaning',
    location: 'Staten Island, NY',
    date: '2026-06-05',
    verified: true,
    visible: true,
  },
  {
    id: 6,
    name: 'James Wilson',
    rating: 4,
    text: 'Solid cleaning service. Professional staff and good communication throughout. Would use again for regular maintenance.',
    service: 'Regular Cleaning',
    location: 'Bronx, NY',
    date: '2026-06-03',
    verified: true,
    visible: false,
  },
  {
    id: 7,
    name: 'Amanda Foster',
    rating: 5,
    text: 'Outstanding work! They cleaned my office space and it looks immaculate. The attention to detail is remarkable.',
    service: 'Commercial Cleaning',
    location: 'New York, NY',
    date: '2026-06-01',
    verified: true,
    visible: true,
  },
  {
    id: 8,
    name: 'Robert Kim',
    rating: 3,
    text: 'Service was okay but not exceptional. Some areas were missed during the cleaning. Hoping for improvement next time.',
    service: 'Regular Cleaning',
    location: 'Brooklyn, NY',
    date: '2026-05-28',
    verified: false,
    visible: true,
  },
];
